# Generated by Django 4.0.2 on 2022-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uesrname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
