# Generated by Django 4.0.2 on 2022-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_uesrname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uesrname',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
