# Generated by Django 3.2.10 on 2022-03-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_uesrname_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
